[client]
showErrorDetails = false
showSidebarNavigation = true

[server]
maxMessageSize = 1024

[theme]
primaryColor="#F7EEED"
backgroundColor="#F6A6BB"
secondaryBackgroundColor="#F7D1D8"
textColor="#262730"
font="sans serif"